RT/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts import views as accounts_views
from django.contrib.auth import views as auth_views, password_validation

from accounts.forms import UserLoginForm, NewPasswordResetForm, NewSetPasswordForm, NewPasswordChangeForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', accounts_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html', authentication_form=UserLoginForm),
         name="login"),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name="logout"),
    path('password-change/', auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html',
                                                                   form_class=NewPasswordChangeForm),
         name='password_change'),
    path('password-change/done',
         auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
                                              form_class=NewPasswordResetForm),
         name="password_reset"),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
                                                     form_class=NewSetPasswordForm),
         name="password_reset_confirm"),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name="password_reset_complete"),
    path('', include('navigation.urls')),
]

cathedra_control/urls.py
from django.conf.urls.static import static
from django.urls import path

from RT import settings
from .views import *

urlpatterns = [

    path('', cathedra_control, name='cathedra_control_url'),
    path('courses/', course_create, name='courses_url'),
    path('courses/course-edit/course_id=<int:course_id>/', course_edit, name='course_edit_url'),
    path('teacher-create/', teacher_create, name='teacher_create_url'),
    path('teacher-edit/teacher_id=<int:teacher_id>/', teacher_edit, name='teacher_edit_url'),
    path('teacher-delete/teacher_id=<int:teacher_id>/', teacher_delete, name='teacher_delete_url'),
    path('add-teacher/teacher_id=<int:teacher_id>/', add_teacher_to_cathedra, name='add_teacher_url'),
    path('add-course-to-teacher/teacher_id=<int:teacher_id>/', add_course_to_teacher, name='add_course_to_teacher_url'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cathedra_control/models.py
from django.db import models

# Create your models here.

cathedra_control/forms.py
from django import forms
from datetime import date

from navigation.models import *

widget = forms.TextInput(attrs={
    'class': 'input__text',
})

s_widget = forms.CheckboxSelectMultiple(attrs={

})
c_widget = forms.TextInput(attrs={'class': 'input__text__short'})


class DateInput(forms.DateInput):
    input_type = 'date'


class TeacherCreateEditForm(forms.ModelForm):
    courses = forms.ModelMultipleChoiceField(queryset=Course.objects.all(), widget=s_widget, label='Курсы',
                                             required=False)
    birth_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}), label='Дата рождения', required=False)
    last_name = forms.CharField(widget=widget, label='Фамилия', required=True)
    first_name = forms.CharField(widget=widget, label='Имя', required=True)
    patronymic = forms.CharField(widget=widget, label='Отчество', required=False)
    speciality = forms.CharField(widget=widget, label='Специальность', required=False)

    class Meta:
        model = Teacher
        fields = ('last_name', 'first_name', 'patronymic', 'courses', 'speciality', 'is_lecturer', 'is_practical',
                  'birth_date', 'avatar',)

    def clean_birth_date(self):
        new_date = self.cleaned_data.get("birth_date")

        if new_date and new_date > date.today():
            raise forms.ValidationError("Введена недопустимая дата")
        return new_date


class CourseCreateForm(forms.ModelForm):
    title = forms.CharField(widget=widget, max_length=50, label='Название курса')

    class Meta:
        model = Course
        fields = ('title',)

    def clean_title(self):
        courses = Course.objects.all()
        titles = []
        for course in courses:
            titles.append(course.title.lower())
        title = self.cleaned_data['title']
        title = title.lower()
        if title in titles:
            raise forms.ValidationError("Курс с таким названием уже существует")
        else:
            return self.cleaned_data['title']


class CourseEditForm(forms.ModelForm):
    title = forms.CharField(widget=widget, max_length=50, label='Название курса')
    teachers = forms.ModelMultipleChoiceField(queryset=Teacher.objects.all(), widget=s_widget, label='Преподаватели',
                                              required=False)

    class Meta:
        model = Course
        fields = ('title', 'teachers',)

    def __init__(self, user, *args, **kwargs):
        super(CourseEditForm, self).__init__(*args, **kwargs)
        self.fields['teachers'].queryset = Teacher.objects.filter(cathedras__title__contains=user.cathedra.title)

    def clean_title(self):
        courses = Course.objects.all()
        titles = []
        for course in courses:
            titles.append(course.title.lower())
        title = self.cleaned_data['title']
        title = title.lower()

        if self.instance.title.lower() == title:
            return self.cleaned_data['title']
        if title in titles:
            raise forms.ValidationError("Курс с таким названием уже существует")
        return self.cleaned_data['title']


widget1 = forms.DateInput(attrs={'type': 'date', 'class': 'date__field}'})


class ReportDatesForm(forms.Form):
    date_1 = forms.DateField(widget=widget1, label='С ')
    date_2 = forms.DateField(widget=widget1, label='По ')

    def clean(self):
        cleaned_data = super().clean()

        date1 = cleaned_data.get('date_1')
        if date1 and date1 > date.today():
            raise forms.ValidationError("Введена недопустимая дата1")

        date2 = cleaned_data.get('date_2')
        if date2 and date2 > date.today():
            raise forms.ValidationError("Введена недопустимая дата2")

        if date1 > date2:
            raise forms.ValidationError("Введен некорректный временной отрезок(дата1 > дата2)")

cathedra_control/views.py
from datetime import timedelta

from django.core.exceptions import ValidationError
from django.core.mail import EmailMessage
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from RT.settings import EMAIL_HOST_USER
from .decorators import *
from .forms import *
from .utils import create_report


@cathedra_head_only
def cathedra_control(request):
    search_query = request.GET.get('search', '___123___')
    teachers = request.user.cathedra.teachers.all()
    other_teachers = Teacher.objects.exclude(cathedras__id__contains=request.user.cathedra.id).filter(
        Q(first_name__icontains=search_query) | Q(last_name__icontains=search_query) |
        Q(patronymic__icontains=search_query))
    if request.method == 'POST':
        form = ReportDatesForm(request.POST)
        if form.is_valid():
            date_1 = form.cleaned_data['date_1']
            date_2 = form.cleaned_data['date_2']
            file = create_report(request.user.cathedra,
                                 date_1,
                                 date_2 + timedelta(days=1))
            email = EmailMessage('Отчет',
                                 f'Доборого времени суток!\nСформирован отчет по кафедре {request.user.cathedra.title} '
                                 f'за период с {date_1.strftime("%d.%m.%Y")} до {date_2.strftime("%d.%m.%Y")}'
                                 f'\n\nС уважением,\nадминистрация сайта ETUrate',
                                 EMAIL_HOST_USER,
                                 [request.user.email])
            email.attach_file(file)
            email.send(fail_silently=False)
            return redirect('cathedra_control_url')
    else:
        form = ReportDatesForm()
    return render(request, 'cathedra_control/cathedra_control.html',
                  context={'teachers': teachers, 'other_teachers': other_teachers, 'form': form})


@cathedra_head_only
def teacher_create(request):
    if request.method == 'POST':
        form = TeacherCreateEditForm(request.POST, request.FILES)
        if form.is_valid():
            teacher = Teacher.objects.create(
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                patronymic=form.cleaned_data['patronymic'],
                speciality=form.cleaned_data['speciality'],
                is_lecturer=form.cleaned_data['is_lecturer'],
                is_practical=form.cleaned_data['is_practical'],
                birth_date=form.cleaned_data['birth_date'],
                avatar=form.cleaned_data['avatar'],
            )
            teacher.cathedras.add(request.user.cathedra)
            for course in form.cleaned_data['courses'].all():
                teacher.courses.add(course)
            return redirect('cathedra_control_url')
    else:
        form = TeacherCreateEditForm()
    return render(request, 'cathedra_control/teacher_create.html', context={'form': form})


@cathedra_head_only
def teacher_edit(request, teacher_id=None):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    if request.method == 'POST':
        form = TeacherCreateEditForm(request.POST, request.FILES, instance=teacher)
        if form.is_valid():
            teacher.courses.through.objects.filter(teacher_id=teacher_id).delete()
            for course in form.cleaned_data['courses'].all():
                teacher.courses.add(course)
            form.save()
            return redirect('cathedra_control_url')
    else:
        form = TeacherCreateEditForm(instance=teacher, initial={'courses': teacher.courses.all()})
    return render(request, 'cathedra_control/teacher_edit.html', context={'form': form})


@cathedra_head_only
def teacher_delete(request, teacher_id=None):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    cathedra = request.user.cathedra
    if request.method == 'POST':
        cathedra.teachers.remove(teacher)
        return redirect('cathedra_control_url')


@cathedra_head_only
def course_create(request):
    courses = Course.objects.all()
    if request.method == 'POST':
        form = CourseCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('courses_url')
    else:
        form = CourseCreateForm()
    return render(request, 'cathedra_control/courses.html', context={'form': form, 'courses': courses})


@cathedra_head_only
def course_edit(request, course_id=None):
    course = get_object_or_404(Course, id=course_id)
    if request.method == 'POST':
        form = CourseEditForm(request.user, request.POST, instance=course)
        if form.is_valid():
            course.teachers.through.objects.filter(course_id=course_id).delete()
            for teacher in form.cleaned_data['teachers'].all():
                course.teachers.add(teacher)
            form.save()
            return redirect('courses_url')
    else:
        form = CourseEditForm(instance=course, user=request.user)
    return render(request, 'cathedra_control/course_edit.html', context={'form': form, 'course': course})


# @cathedra_head_only
# def course_delete(request, course_id=None):
#     course = get_object_or_404(Course, id=course_id)
#     if request.method == 'POST':
#         course.delete()
#         return redirect('courses_url')


@cathedra_head_only
def add_teacher_to_cathedra(request, teacher_id=None):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    if request.method == 'POST':
        request.user.cathedra.teachers.add(teacher)
        return redirect('cathedra_control_url')


@cathedra_head_only
def add_course_to_teacher(request, teacher_id=None):
    teacher = get_object_or_404(Teacher, id=teacher_id)
    courses = teacher.courses.all()
    if request.method == 'POST':
        form = CourseCreateForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']
            course = Course.objects.filter(title=title).first()
            if course is None:
                course = Course(title=title)
                course.save()
            teacher.courses.add(course)
        return redirect('add_course_to_teacher_url', teacher_id)
    else:
        form = CourseCreateForm()
    return render(request, 'cathedra_control/add_course_to_teacher.html', context={'form': form, 'courses': courses,
                                                                                   'teacher': teacher})

cathedra_control/templates/cathedra_control/add_course_to_teacher.html
{% extends 'base.html' %}

{% block title %}
Курсы преподавателя
{% endblock %}

{% block content %}
<h2>{{ teacher.last_name }} {{ teacher.first_name }} {{ teacher.patronymic }}</h2>
<div class="content=section">
    <form method="post" enctype="multipart/form-data" class="form-group">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Добавить курс</legend>
            {{ form }}
        </fieldset>
        <div class="form-group">
            <button type="submit" class="btn btn-outline-info">Добавить</button>
        </div>
    </form>
</div>
    <h3>Курсы</h3>
    {% for course in courses %}
        <h4>{{ course.title }}</h4>
    {% endfor %}
{% endblock %}

cathedra_control/templates/cathedra_control/cathedra_control.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Управление кафедрой
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'cathedra_control/css/cathedra_control.css' %}">

    <div class="cathedra__title">Кафедра: <a href="{{ user.cathedra.get_absolute_url }}">{{ user.cathedra.title }}</a>
    </div>
    {% if teachers.all %}
        <div class="report__container">
            <h1>Выберите период для формирования отчета об успехах преподавателей!</h1>
            <h2>Введите даты</h2>
            <form method="post">
                {% csrf_token %}
                <div class="date__form">
                    <p style="margin-right: 10px">{{ form.date_1.label }}</p>
                    {{ form.date_1 }}
                    <p style="margin: 10px">{{ form.date_2.label }}</p>
                    {{ form.date_2 }}
                </div>
                <button type="submit" class="submit__form">Сформировать отчет</button>
            </form>
            {% for field, errors in form.errors.items %}
                <ul class="errorlist">
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </div>
    {% endif %}
    <div class="cathedra__title">Преподаватели:</div>
    <div class="teachers__container">
        {% for teacher in teachers %}
            <div class="teacher__card">
                <img class="card__image" src="{{ teacher.avatar.url }}" alt="Аватар">
                <div class="teacher__info">
                    <a class="teacher__name" href="{{ teacher.get_absolute_url }}">{{ teacher }}</a>
                    <form method="get" action="{% url 'teacher_edit_url' teacher_id=teacher.id %}">
                        {% csrf_token %}
                        <button type="submit" class="submit__form">Изменить</button>
                    </form>
                    <form method="post" action="{% url 'teacher_delete_url' teacher_id=teacher.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete__btn">Удалить с кафедры</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="btns">
        <form action="{% url 'teacher_create_url' %}">

            <button class="submit__form">Добавить преподавателя</button>
        </form>
        <form action="{% url 'courses_url' %}">
            <button class="submit__form">Курсы</button>
        </form>
    </div>

    <div class="cathedra__title">Преподаватели с других кафедр:</div>
    <form class="search" action="{% url 'cathedra_control_url' %}">
        <input class="search__bar" placeholder="Поиск" type="text" name="search">
        <input type="image" class="search__submit" src="{% static 'main/img/Button_Search.png' %}">
    </form>
    <div class="teachers__container">
        {% for teacher in other_teachers %}
            <div class="teacher__card">
                <img class="card__image" src="{{ teacher.avatar.url }}" alt="Аватар">
                <div class="teacher__info">
                    <a class="teacher__name" href="{{ teacher.get_absolute_url }}">{{ teacher }}</a>

                    <form method="post" action="{% url 'add_teacher_url' teacher_id=teacher.id %}">
                        {% csrf_token %}
                        <button type="submit" class="add__to__cathedra">Добавить на кафедру</button>
                    </form>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

cathedra_control/templates/cathedra_control/course_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Изменить курс
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'cathedra_control/css/cathedra_control.css' %}">
    <div class="form__container">
        <div class="form__title">Изменить курс</div>
        <form method="post">
            {% csrf_token %}
            <div class="course__container">
                <div class="input__container" id="course__left">
                    <div class="input__label" for="input__text"> {{ form.title.label }}</div>
                    {{ form.title }}
                </div>
                <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.teachers.label }}</div>
                    <input type="text" id="teacher_name" class="input__text">
                    <br>
                    {{ form.teachers }}
                </div>
            </div>
            {% for field, errors in form.errors.items %}
                <ul class="errorlist">
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
            <button class="submit__form" type="submit">Добавить изменения</button>
        </form>


    </div>
    <script>
        document.querySelector("#teacher_name").oninput = function() {
            let val = this.value.trim().toLowerCase();
            let elasticItems = document.querySelectorAll("#id_teachers li label");
            if (val != "") {
                elasticItems.forEach(function(elem) {
                    if (elem.innerText.toLowerCase().search(val) == -1) {
                        elem.style.display = "none";
                    }
                    else {
                        elem.style.display = 'block';
                    }
                });
            }
            else {
                elasticItems.forEach(function(elem) {
                    elem.style.display = 'block'
                });
            }
        }
    </script>
{% endblock %}

cathedra_control/templates/cathedra_control/courses.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Курсы
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'cathedra_control/css/cathedra_control.css' %}">
    <div class="form__container">
        <div class="form__title">Добавить курс</div>
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
                <div class="input__container">
                    <div class="input__label" for="input__text">{{ field.label }}</div>
                    {{ field }}
                </div>
            {% endfor %}
            {% for field, errors in form.errors.items %}
                <ul class="errorlist">
                    {% for error in errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
            <button class="submit__form" type="submit">Добавить</button>
        </form>
        <br>
        <div class="input__label" for="input__text">Поиск по курсам</div>
        <input type="text" id="elastic" class="input__text">
        <div class="courses">
            {% for course in courses %}
                <a href="{% url 'course_edit_url' course_id=course.id %}" class="input__label">{{ course.title }}</a>
            {% endfor %}
        </div>
    </div>

    <script>
        document.querySelector("#elastic").oninput = function() {
            let val = this.value.trim().toLowerCase();
            let elasticItems = document.querySelectorAll(".courses a");
            if (val != "") {
                elasticItems.forEach(function(elem) {
                    if (elem.innerText.toLowerCase().search(val) == -1) {
                        elem.style.display = "none";
                    }
                    else {
                        elem.style.display = 'block';
                    }
                });
            }
            else {
                elasticItems.forEach(function(elem) {
                    elem.style.display = 'block'
                });
            }
        }
    </script>
{% endblock %}

cathedra_control/templates/cathedra_control/teacher_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Добавить преподавателя
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'cathedra_control/css/cathedra_control.css' %}">
<div class="form__container">
        <div class="form__title">Добавить преподавателя</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.last_name.label }}</div>
                    {{ form.last_name }}
            </div>
            <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.first_name.label }}</div>
                    {{ form.first_name }}
            </div>
            <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.patronymic.label }}</div>
                    {{ form.patronymic }}
            </div>
            <div class="many__to__many">
                <div class="left">
                    <div class="input__container">
                        <div class="input__label" for="input__text"> {{ form.speciality.label }}</div>
                        {{ form.speciality }}
                    </div>
                    <div id="check">
                        {{ form.is_lecturer }}
                        <div class="input__label"  for="input__text"> {{ form.is_lecturer.label }}</div>
                    </div>
                    <div  id="check">
                        {{ form.is_practical }}
                        <div class="input__label" for="input__text"> {{ form.is_practical.label }}</div>
                    </div>
                    <div  id="birth">
                        <div class="input__label" for="input__text"> {{ form.birth_date.label }}</div>
                        {{ form.birth_date }}
                    </div>
                    <div class="input__container">
                        <div class="input__label" for="input__text"> {{ form.avatar.label }}</div>
                        {{ form.avatar }}
                    </div>
                </div>
                <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.courses.label }}</div>
                    <input type="text" id="course_title" class="input__text">
                    <br>
                    {{ form.courses }}
                </div>
            </div>
            <button class="submit__form" type="submit">Добавить</button>
        </form>
    </div>

    <script>
        document.querySelector("#course_title").oninput = function() {
            let val = this.value.trim().toLowerCase();
            let elasticItems = document.querySelectorAll("#id_courses li label");
            if (val != "") {
                elasticItems.forEach(function(elem) {
                    if (elem.innerText.toLowerCase().search(val) == -1) {
                        elem.style.display = "none";
                    }
                    else {
                        elem.style.display = 'block';
                    }
                });
            }
            else {
                elasticItems.forEach(function(elem) {
                    elem.style.display = 'block';
                });
            }
        }
    </script>
{% endblock %}

cathedra_control/templates/cathedra_control/teacher_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Изменить преподавателя
{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'cathedra_control/css/cathedra_control.css' %}">
    <div class="form__container">
        <div class="form__title">Изменить преподавателя</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input__container">
                <div class="input__label" for="input__text"> {{ form.last_name.label }}</div>
                {{ form.last_name }}
            </div>
            <div class="input__container">
                <div class="input__label" for="input__text"> {{ form.first_name.label }}</div>
                {{ form.first_name }}
            </div>
            <div class="input__container">
                <div class="input__label" for="input__text"> {{ form.patronymic.label }}</div>
                {{ form.patronymic }}
            </div>
            <div class="many__to__many">
                <div class="left">
                    <div class="input__container">
                        <div class="input__label" for="input__text"> {{ form.speciality.label }}</div>
                        {{ form.speciality }}
                    </div>
                    <div id="check">
                        {{ form.is_lecturer }}
                        <div class="input__label" for="input__text"> {{ form.is_lecturer.label }}</div>
                    </div>
                    <div id="check">
                        {{ form.is_practical }}
                        <div class="input__label" for="input__text"> {{ form.is_practical.label }}</div>
                    </div>
                    <div id="birth">
                        <div class="input__label" for="input__text"> {{ form.birth_date.label }}</div>
                        {{ form.birth_date }}
                    </div>
                    <div >
                        <div class="input__label" for="input__text"> {{ form.avatar.label }}</div>
                        {{ form.avatar }}
                    </div>
                </div>
                <div class="input__container">
                    <div class="input__label" for="input__text"> {{ form.courses.label }}</div>
                    <input type="text" id="course_title" class="input__text">
                    <br>
                    {{ form.courses }}
                </div>
            </div>
            <button class="submit__form" type="submit">Изменить</button>
        </form>
    </div>

    <script>
        document.querySelector("#course_title").oninput = function() {
            let val = this.value.trim().toLowerCase();
            let elasticItems = document.querySelectorAll("#id_courses li label");
            if (val != "") {
                elasticItems.forEach(function(elem) {
                    if (elem.innerText.toLowerCase().search(val) == -1) {
                        elem.style.display = "none";
                    }
                    else {
                        elem.style.display = 'block';
                    }
                });
            }
            else {
                elasticItems.forEach(function(elem) {
                    elem.style.display = 'block';
                });
            }
        }
    </script>
{% endblock %}